### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [zhiweichen0012/CATR#1]
Thank you very much for your excellent work on the weakly supervised object localization task.
I was wondering if you plan to release your code anytime soon.

**Comment by zhiweichen0012** [comment]
Thank you very much for your interest in our work! We expect to make the code public next week. 

We apologize for the late release of the code due to the recent busy schedule.

**Comment by zhiweichen0012** [comment]
Thank you for your patience, the code has been made public.
