### ISSUE TITLE
the difference between "CATR_cub" and "CATR_imnet"

### ISSUE THREAD

**Issue by iefengjian** [zhiweichen0012/CATR#2]
Thank you for your excellent work on the weakly supervised object localization task!
There are two net in "models.py", I want to train on my own datasets, which net could i choose?

**Comment by zhiweichen0012** [comment]
Thank you very much for your interest in our work! 

"CATR_cub" and "CATR_imnet" are CATR models constructed for the CUB and IMNET datasets, respectively. If you want to train on your own dataset, you can build a new class based on "CATR_cub" or "CATR_imnet", and note that the number of prediction categories and other parameters of this new class need to be adjusted according to your dataset.

I hope the above information is helpful to you.

**Comment by iefengjian** [comment]
OK, thanks!
