### ISSUE TITLE
权重推理时，达不到论文中的效果

### ISSUE THREAD

**Issue by pohunshi** [zhiweichen0012/CATR#4]
作者您好，我在使用您在git上的权重推理CUB时，只得到了如下的结果：
Not using distributed mode
Namespace(aa='rand-m9-mstd0.5-inc1', batch_size=64, clip_grad=None, color_jitter=0.4, cooldown_epochs=10, cutmix=1.0, cutmix_minmax=None, data_path='/home/rjy/lm/CUB_split', data_set='CUB', decay_epochs=30, decay_rate=0.1, device='cuda', dist_eval=False, dist_url='env://', distillation_alpha=0.5, distillation_tau=1.0, distillation_type='none', distributed=False, drop=0.0, drop_path=0.1, epochs=300, eval=True, finetune='', inat_category='name', input_size=224, lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, min_lr=1e-05, mixup=0.8, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, model='deit_small_patch16_224_CATR_cub', model_ema=True, model_ema_decay=0.99996, model_ema_force_cpu=False, momentum=0.9, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='', patience_epochs=10, pin_mem=True, recount=1, remode='pixel', repeated_aug=True, reprob=0.25, resplit=False, resume='CATR_model_epoch80.pth', sched='cosine', seed=0, smoothing=0.1, start_epoch=0, teacher_model='regnety_160', teacher_path='', train_eval=False, train_interpolation='bicubic', warmup_epochs=5, warmup_lr=1e-06, weight_decay=0.05, world_size=1)
Creating model: deit_small_patch16_224_CATR_cub
number of params: 22929159
Loading weights from CATR_model_epoch80.pth.
Test:  [ 0/91]  eta: 0:02:32  acc1: 79.6875 (79.6875)  acc5: 96.8750 (96.8750)  time: 1.6777  data: 0.9290  max mem: 2351
Test:  [10/91]  eta: 0:00:31  acc1: 85.9375 (84.5170)  acc5: 96.8750 (97.0170)  time: 0.3870  data: 0.0849  max mem: 2363
Test:  [20/91]  eta: 0:00:21  acc1: 85.9375 (82.5893)  acc5: 98.4375 (97.1726)  time: 0.2408  data: 0.0003  max mem: 2363
Test:  [30/91]  eta: 0:00:17  acc1: 81.2500 (82.4093)  acc5: 98.4375 (97.6310)  time: 0.2316  data: 0.0001  max mem: 2363
Test:  [40/91]  eta: 0:00:14  acc1: 87.5000 (83.7652)  acc5: 98.4375 (97.6753)  time: 0.2442  data: 0.0001  max mem: 2363
Test:  [50/91]  eta: 0:00:11  acc1: 85.9375 (83.6703)  acc5: 96.8750 (97.3652)  time: 0.2399  data: 0.0001  max mem: 2363
Test:  [60/91]  eta: 0:00:08  acc1: 82.8125 (82.9150)  acc5: 95.3125 (97.0287)  time: 0.2333  data: 0.0001  max mem: 2363
Test:  [70/91]  eta: 0:00:05  acc1: 82.8125 (82.5484)  acc5: 95.3125 (96.9410)  time: 0.2339  data: 0.0001  max mem: 2363
Test:  [80/91]  eta: 0:00:02  acc1: 87.5000 (83.3719)  acc5: 96.8750 (96.9522)  time: 0.2215  data: 0.0001  max mem: 2363
Test:  [90/91]  eta: 0:00:00  acc1: 90.6250 (84.2251)  acc5: 98.4375 (97.0832)  time: 0.2103  data: 0.0001  max mem: 2363
Test: Total time: 0:00:22 (0.2486 s / it)
* Loc Acc@1 [32m79.979[0m Acc@5 91.905 GT [32m94.512[0m TH [4m0.100[0m TestNum 5794
* Acc@1 [32m84.225 [0m Acc@5 97.083
79.979 91.905 94.512 0.100 84.225 97.083
==========
==========
Loc@1: 79.979	 Loc@5: 91.905	 Loc_GT: 94.512	 GT: 0.100
Cls@1: 84.225	 Cls@5: 97.083
79.979 91.905 94.512 0.100 84.225 97.083
您能告诉我哪里出现了问题吗

**Comment by zhiweichen0012** [comment]
您好，首先感谢您对本工作的关注与支持！
1）请您检查环境是否与本仓库要求一致，如CUDA版本为cuda_11.3.0等；
2）本人本地跑的GitHub模型推理日志如下：
```
Not using distributed mode
Namespace(aa='rand-m9-mstd0.5-inc1', batch_size=64, clip_grad=None, color_jitter=0.4, cooldown_epochs=10, cutmix=1.0, cutmix_minmax=None, data_path='datasets/CUB', data_set='CUB', decay_epochs=30, decay_rate=0.1, device='cuda', dist_eval=False, dist_url='env://', distillation_alpha=0.5, distillation_tau=1.0, distillation_type='none', distributed=False, drop=0.0, drop_path=0.1, epochs=300, eval=True, finetune='', inat_category='name', input_size=224, lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, min_lr=1e-05, mixup=0.8, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, model='deit_small_patch16_224_CATR_cub', model_ema=True, model_ema_decay=0.99996, model_ema_force_cpu=False, momentum=0.9, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='', patience_epochs=10, pin_mem=True, recount=1, remode='pixel', repeated_aug=True, reprob=0.25, resplit=False, resume='output_ckpt/CUB/model_epoch80.pth', sched='cosine', seed=0, smoothing=0.1, start_epoch=0, teacher_model='regnety_160', teacher_path='', train_eval=False, train_interpolation='bicubic', warmup_epochs=5, warmup_lr=1e-06, weight_decay=0.05, world_size=1)
Creating model: deit_small_patch16_224_CATR_cub
number of params: 22929159
Loading weights from output_ckpt/CUB/model_epoch80.pth.
Test:  [ 0/91]  eta: 0:02:45  acc1: 78.1250 (78.1250)  acc5: 96.8750 (96.8750)  time: 1.8173  data: 1.3707  max mem: 2351
Test:  [10/91]  eta: 0:00:24  acc1: 85.9375 (84.3750)  acc5: 96.8750 (97.0170)  time: 0.3070  data: 0.1248  max mem: 2363
Test:  [20/91]  eta: 0:00:16  acc1: 85.9375 (82.5149)  acc5: 98.4375 (97.1726)  time: 0.1475  data: 0.0002  max mem: 2363
Test:  [30/91]  eta: 0:00:12  acc1: 81.2500 (82.4093)  acc5: 98.4375 (97.6815)  time: 0.1370  data: 0.0002  max mem: 2363
Test:  [40/91]  eta: 0:00:09  acc1: 87.5000 (83.8034)  acc5: 98.4375 (97.7134)  time: 0.1339  data: 0.0002  max mem: 2363
Test:  [50/91]  eta: 0:00:07  acc1: 85.9375 (83.7010)  acc5: 96.8750 (97.3958)  time: 0.1346  data: 0.0002  max mem: 2363
Test:  [60/91]  eta: 0:00:05  acc1: 82.8125 (82.9406)  acc5: 95.3125 (97.0543)  time: 0.1352  data: 0.0002  max mem: 2363
Test:  [70/91]  eta: 0:00:03  acc1: 82.8125 (82.5704)  acc5: 95.3125 (96.9630)  time: 0.1334  data: 0.0002  max mem: 2363
Test:  [80/91]  eta: 0:00:01  acc1: 87.5000 (83.3912)  acc5: 96.8750 (96.9715)  time: 0.1301  data: 0.0001  max mem: 2363
Test:  [90/91]  eta: 0:00:00  acc1: 90.6250 (84.2423)  acc5: 98.4375 (97.1004)  time: 0.1276  data: 0.0001  max mem: 2363
Test: Total time: 0:00:14 (0.1562 s / it)
* Loc Acc@1 [32m80.066[0m Acc@5 91.992 GT [32m94.581[0m TH [4m0.100[0m TestNum 5794
* Acc@1 [32m84.242 [0m Acc@5 97.100
80.066 91.992 94.581 0.100 84.242 97.100
```
